version: '3.8'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: postgres:17.0-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
