version: '3.8'

services:
  database:
    build:

      dockerfile: Dockerfile.db
    image: postgres:17.0-alpine

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "${DB_PORT}:${DB_PORT}"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      
    environment:

      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@database:${DB_PORT}/${DB_NAME}?schema=public
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
